### PR TITLE
Add 99.99% of TODO's in mba, update the sandbox.

### PR DESCRIPTION
**Pull request by Smellon69**
Coded on my MacBook, no idea if this works. Feel free to test and if it's working remove the print for the generated license key and push to master.

### CODE REVIEW

**Comment by Smellon69** [comment]
don't push this garbage, nothing works... I'll recode it and make it work on linux/windows sense I have to use an online compiler.

**Comment by Smellon69** [comment]
I think I did a thing

**Comment by Smellon69** [comment]
broke broke broke, working on it.

**Comment by notpidgey** [comment]
The reason MBA is not implemented and is because this is not how you do MBA. There's plenty of other things in this project that exist but serve no function.... because there's a thing called "work in progress". Just because things exist in the project doesn't mean they have to be finished. 

Everything inside this project is "fake mba generation". It's not likely that MBA generation will be getting implemented any time soon until its done right. There's really no point in adding truths like this as its mostly pointless and can all be generated. You can also see this https://link.springer.com/chapter/10.1007/978-3-540-77535-5_5 under the chapter "Information Hiding in Software with Mixed Boolean-Arithmetic Transforms".

Feel free to read Ninon Eyrolles' paper for clarification. 
> Ninon Eyrolles. Obfuscation with Mixed Boolean-Arithmetic Expressions : reconstruction, analysis
and simplification tools. Cryptography and Security [cs.CR]. Université Paris Saclay (COmUE), 2017.
English. ffNNT : 2017SACLV031ff. fftel-01623849

Or [Justus Polzin](https://plzin.github.io/)'s condensed blog for clarification.

The only real part of this is the inversion of affine functions inside of "bottom_insert_identity" which comes from the paper linked in the function https://hal.science/hal-01388109v1/document. This entire thing is a mess which requires a lot more than just adding identities to fix. It's just entirely conceptually wrong.

I'm in the process of getting the findings in these papers into code, but its not easy. And it will *probably* be done eventually.

There is no reason to update sandbox with this. This wouldn't make for a good crack me either. For one, this relies on STL functions which are not virtualized because the function body of whatever STL operator override or function is called is not virtualized. This means that someone just can see the calls to string operators and random which will be enough to solve. Also, its completely unfair to rely on a completely random flag like this.

TODOs are not a good source of finding things to contribute (most of the time). A lot of it is just me writing my thoughts down. This is primarily my fault because at the moment this is more of a personal project and is in the process of transitioning to the project. Should've made this clearer.

There's nothing to PR here. Sorry. Also please make an effort to not just PR random stuff without testing. I was going to type a very frustrated response to this, but I decided not to. I do not want to block you from the repository, please take a break from opening issues.

**Pull request closed without merging**
